version: '3'
services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - .env
    command: ["streamlit", "run", "your_script.py"]
